# Generated by Django 4.0.2 on 2022-03-18 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=enum.auto)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 19, 25, 25, 275818), verbose_name='date_created')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to=settings.AUTH_USER_MODEL, verbose_name='Manage_id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=enum.auto)),
                ('Name', models.CharField(max_length=30, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 19, 25, 25, 276324), verbose_name='date_created')),
                ('Status', models.CharField(choices=[('hot', 'hot'), ('cold', 'cold'), ('med', 'med'), ('sold', 'sold')], max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
        ),
    ]
