# Generated by Django 4.0.2 on 2022-03-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='SiteUser',
        ),
    ]
