# Generated by Django 4.0.2 on 2022-03-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_register_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
