# Generated by Django 4.0.2 on 2022-03-18 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_alter_lead_created_at_alter_siteuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='Manager_is',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to=settings.AUTH_USER_MODEL, verbose_name='Manage_id'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 19, 45, 1, 251164), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 19, 45, 1, 250650), verbose_name='date_created'),
        ),
    ]
