# Generated by Django 4.0.2 on 2022-03-04 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_siteuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_created'),
        ),
    ]
