# Generated by Django 4.0.2 on 2022-03-04 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_siteuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 22, 3, 26, 304717), verbose_name='date_created'),
        ),
    ]
