# Generated by Django 4.0.2 on 2022-03-08 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_siteuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 19, 4, 14, 766873), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
