# Generated by Django 4.0.2 on 2022-03-08 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_siteuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='id',
            new_name='Staff_id',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 19, 7, 41, 891938), verbose_name='date_created'),
        ),
    ]
