# Generated by Django 4.0.2 on 2022-03-08 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_id_siteuser_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='Staff_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 19, 9, 18, 447662), verbose_name='date_created'),
        ),
    ]
