# Generated by Django 4.0.2 on 2022-03-08 16:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_rename_staff_id_siteuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 21, 58, 58, 660338), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=enum.auto),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=enum.auto)),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 8, 21, 58, 58, 707245), verbose_name='date_created')),
                ('State', models.CharField(choices=[('hot', 'hot'), ('cold', 'cold'), ('med', 'med'), ('sold', 'sold')], max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.siteuser')),
            ],
        ),
    ]
