# Generated by Django 4.0.2 on 2022-03-08 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_siteuser_created_at_alter_siteuser_id_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 22, 45, 30, 848810), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 8, 22, 45, 30, 801189), verbose_name='date_created'),
        ),
    ]
