# Generated by Django 4.0.2 on 2022-03-12 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_lead_created_at_alter_siteuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='State',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 18, 56, 47, 571080), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 18, 56, 47, 476439), verbose_name='date_created'),
        ),
    ]
