# Generated by Django 4.0.2 on 2022-03-12 13:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0014_rename_state_lead_status_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 18, 58, 47, 981360), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 18, 58, 47, 981360), verbose_name='date_created'),
        ),
    ]
