# Generated by Django 4.0.2 on 2022-03-22 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_alter_lead_created_at_alter_siteuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remark',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 23, 3, 31, 759115), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 23, 3, 31, 759115), verbose_name='date_created'),
        ),
    ]
