# Generated by Django 4.0.2 on 2022-03-24 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_alter_lead_created_at_alter_lead_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='remarks_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 0, 45, 5, 256546), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='remark',
            field=models.TextField(choices=[('add', 'add'), ('view', 'view')], default='add'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 0, 45, 5, 257055), verbose_name='date_created'),
        ),
    ]
