# Generated by Django 4.0.2 on 2022-03-24 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_lead_remarks_data_alter_lead_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 0, 45, 55, 766498), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='remark',
            field=models.CharField(choices=[('add', 'add'), ('view', 'view')], default='add', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 0, 45, 55, 767003), verbose_name='date_created'),
        ),
    ]
