# Generated by Django 4.0.2 on 2022-03-24 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_alter_lead_created_at_alter_lead_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 0, 48, 48, 25523), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='remark',
            field=models.TextField(default='Add+'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 0, 48, 48, 26028), verbose_name='date_created'),
        ),
    ]
