# Generated by Django 4.0.2 on 2022-03-26 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_alter_lead_created_at_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 11, 47, 9, 706213), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/profile.png', upload_to='static/userImages/'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 11, 47, 9, 706213), verbose_name='date_created'),
        ),
    ]
